-- ====================================================================
-- E-Commerce Sales & Customer Analytics - 100 SQL Query Library
-- DBMS: MySQL
-- ====================================================================

USE ecommerce_analytics;

-- ====================================================================
-- SECTION 1: Basic Selection, Filtering, and Sorting (Queries 1-15)
-- ====================================================================

-- 1. Retrieve all columns from the categories table
SELECT * FROM categories;

-- 2. List the first 10 customers sorted by city alphabetically
SELECT * FROM customers 
ORDER BY customer_city ASC 
LIMIT 10;

-- 3. Retrieve unique states where customers are located
SELECT DISTINCT customer_state FROM customers;

-- 4. Find all products belonging to the 'electronics' category
SELECT * FROM products 
WHERE product_category_name = 'electronics';

-- 5. List orders with 'canceled' status
SELECT * FROM orders 
WHERE order_status = 'canceled';

-- 6. Find products with a base price greater than $500
SELECT * FROM products 
WHERE product_base_price > 500.00;

-- 7. Retrieve sellers located in the state of 'SP' (São Paulo)
SELECT * FROM sellers 
WHERE seller_state = 'SP';

-- 8. Find orders placed between January 1, 2025, and January 31, 2025
SELECT * FROM orders 
WHERE order_purchase_timestamp BETWEEN '2025-01-01 00:00:00' AND '2025-01-31 23:59:59';

-- 9. List products that have between 3 and 5 photos
SELECT * FROM products 
WHERE product_photos_qty BETWEEN 3 AND 5;

-- 10. Find customers whose city name starts with 'Belo'
SELECT * FROM customers 
WHERE customer_city LIKE 'Belo%';

-- 11. Find reviews where the score is either 1 or 2 (low satisfaction)
SELECT * FROM reviews 
WHERE review_score IN (1, 2);

-- 12. Find orders where the carrier delivery date is NULL (shipped but not yet received by carrier, or processing)
SELECT * FROM orders 
WHERE order_delivered_carrier_date IS NULL;

-- 13. Find reviews that have a comment title
SELECT * FROM reviews 
WHERE review_comment_title IS NOT NULL AND review_comment_title <> '';

-- 14. List products sorted by weight descending, showing the top 5 heaviest
SELECT * FROM products 
ORDER BY product_weight_g DESC 
LIMIT 5;

-- 15. Retrieve return requests that are currently 'pending'
SELECT * FROM returns 
WHERE return_status = 'pending';


-- ====================================================================
-- SECTION 2: Aggregations, Grouping, and Filtering on Aggregations (Queries 16-30)
-- ====================================================================

-- 16. Count the total number of orders in the database
SELECT COUNT(*) AS total_orders FROM orders;

-- 17. Find the minimum, maximum, and average product base price
SELECT 
    MIN(product_base_price) AS min_price, 
    MAX(product_base_price) AS max_price, 
    AVG(product_base_price) AS avg_price 
FROM products;

-- 18. Count the number of customers in each state
SELECT customer_state, COUNT(*) AS customer_count 
FROM customers 
GROUP BY customer_state 
ORDER BY customer_count DESC;

-- 19. Find the total quantities sold for each product
SELECT product_id, SUM(quantity) AS total_qty_sold 
FROM order_items 
GROUP BY product_id 
ORDER BY total_qty_sold DESC;

-- 20. Count orders by their current status
SELECT order_status, COUNT(*) AS status_count 
FROM orders 
GROUP BY order_status;

-- 21. Get the average review score given by customers
SELECT AVG(review_score) AS average_review_score FROM reviews;

-- 22. Find the total revenue (excluding shipping) generated by the company
SELECT SUM(price * quantity) AS total_product_revenue FROM order_items;

-- 23. Find the total freight value paid across all orders
SELECT SUM(freight_value) AS total_freight_paid FROM order_items;

-- 24. List product categories and their total products count
SELECT product_category_name, COUNT(*) AS product_count 
FROM products 
GROUP BY product_category_name 
ORDER BY product_count DESC;

-- 25. Find states with more than 100 sellers
SELECT seller_state, COUNT(*) AS seller_count 
FROM sellers 
GROUP BY seller_state 
HAVING seller_count > 100;

-- 26. List product categories with average prices above $200
SELECT product_category_name, AVG(product_base_price) AS avg_price 
FROM products 
GROUP BY product_category_name 
HAVING avg_price > 200.00;

-- 27. Find orders that contain more than 3 items
SELECT order_id, SUM(quantity) AS total_items 
FROM order_items 
GROUP BY order_id 
HAVING total_items > 3;

-- 28. Find the count of return requests grouped by reason
SELECT return_reason, COUNT(*) AS return_count 
FROM returns 
GROUP BY return_reason;

-- 29. Count the number of reviews grouped by review score
SELECT review_score, COUNT(*) AS review_count 
FROM reviews 
GROUP BY review_score 
ORDER BY review_score DESC;

-- 30. Get the average installments count for credit card payments
SELECT AVG(payment_installments) AS avg_installments 
FROM payments 
WHERE payment_type = 'credit_card';


-- ====================================================================
-- SECTION 3: Relational Joins (Queries 31-45)
-- ====================================================================

-- 31. Join orders and customers to see which customer (unique ID) placed which order
SELECT o.order_id, c.customer_unique_id, o.order_purchase_timestamp 
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id;

-- 32. Retrieve order items details along with English category name
SELECT oi.order_item_id, oi.order_id, p.product_id, cat.product_category_name_english, oi.price 
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
INNER JOIN categories cat ON p.product_category_name = cat.product_category_name;

-- 33. Left Join to list all customers and their order status (including those who haven't ordered, if any)
SELECT c.customer_unique_id, o.order_id, o.order_status 
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id;

-- 34. Calculate total revenue generated by each seller
SELECT s.seller_id, s.seller_state, SUM(oi.price * oi.quantity) AS total_revenue 
FROM order_items oi
INNER JOIN sellers s ON oi.seller_id = s.seller_id
GROUP BY s.seller_id, s.seller_state
ORDER BY total_revenue DESC;

-- 35. Find average delivery time (days) for each shipping carrier
SELECT sh.shipping_carrier, AVG(DATEDIFF(sh.shipping_actual_delivery_date, o.order_purchase_timestamp)) AS avg_delivery_days 
FROM shipping sh
INNER JOIN orders o ON sh.order_id = o.order_id
WHERE sh.shipping_status = 'delivered'
GROUP BY sh.shipping_carrier;

-- 36. Find average review score for each product category (English name)
SELECT cat.product_category_name_english, AVG(r.review_score) AS avg_score, COUNT(r.review_id) AS total_reviews
FROM reviews r
INNER JOIN orders o ON r.order_id = o.order_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
INNER JOIN categories cat ON p.product_category_name = cat.product_category_name
GROUP BY cat.product_category_name_english
ORDER BY avg_score DESC;

-- 37. List products that have never been ordered (if any)
SELECT p.product_id, p.product_category_name, p.product_base_price 
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

-- 38. Self Join: Find pairs of customers living in the same city and state (limited to 20 pairs)
SELECT c1.customer_unique_id AS customer_1, c2.customer_unique_id AS customer_2, c1.customer_city, c1.customer_state
FROM customers c1
INNER JOIN customers c2 ON c1.customer_city = c2.customer_city 
    AND c1.customer_state = c2.customer_state 
    AND c1.customer_unique_id < c2.customer_unique_id
LIMIT 20;

-- 39. Combine reviews and returns to see if returned products had poor review scores
SELECT r.return_id, r.order_id, r.product_id, rev.review_score, r.return_reason 
FROM returns r
INNER JOIN reviews rev ON r.order_id = rev.order_id;

-- 40. Get breakdown of payment methods and their total contribution to revenue
SELECT p.payment_type, SUM(p.payment_value) AS total_payment_value, COUNT(DISTINCT p.order_id) AS total_orders
FROM payments p
GROUP BY p.payment_type
ORDER BY total_payment_value DESC;

-- 41. Find top 5 cities with highest sales revenue
SELECT c.customer_city, SUM(oi.price * oi.quantity) AS city_revenue 
FROM order_items oi
INNER JOIN orders o ON oi.order_id = o.order_id
INNER JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY city_revenue DESC
LIMIT 5;

-- 42. Get number of delayed deliveries grouped by state
SELECT c.customer_state, COUNT(o.order_id) AS delayed_orders_count 
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
WHERE o.order_status = 'delivered' AND o.order_delivered_customer_date > o.order_estimated_delivery_date
GROUP BY c.customer_state
ORDER BY delayed_orders_count DESC;

-- 43. Multi-table join to retrieve full customer order history profile
SELECT 
    o.order_id, c.customer_unique_id, o.order_status, 
    SUM(oi.price * oi.quantity) AS items_cost, 
    SUM(oi.freight_value) AS freight_cost,
    SUM(p.payment_value) AS amount_paid
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN payments p ON o.order_id = p.order_id
GROUP BY o.order_id, c.customer_unique_id, o.order_status
LIMIT 10;

-- 44. Find the average return rate of items sold by seller state
SELECT s.seller_state, COUNT(r.return_id) AS returns_count, COUNT(oi.order_item_id) AS items_sold, (COUNT(r.return_id) / COUNT(oi.order_item_id)) * 100 AS return_rate
FROM order_items oi
INNER JOIN sellers s ON oi.seller_id = s.seller_id
LEFT JOIN returns r ON oi.order_id = r.order_id AND oi.product_id = r.product_id
GROUP BY s.seller_state
ORDER BY return_rate DESC;

-- 45. Join orders with payments and check if any payment value is less than total order value (discrepancy check)
SELECT o.order_id, SUM(oi.price * oi.quantity + oi.freight_value) AS order_total, SUM(p.payment_value) AS payments_total
FROM orders o
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN payments p ON o.order_id = p.order_id
GROUP BY o.order_id
HAVING payments_total < order_total - 0.05
LIMIT 10;


-- ====================================================================
-- SECTION 4: Advanced Subqueries and Common Table Expressions (CTEs) (Queries 46-60)
-- ====================================================================

-- 46. Find products with price above the overall average product price
SELECT product_id, product_category_name, product_base_price 
FROM products 
WHERE product_base_price > (SELECT AVG(product_base_price) FROM products);

-- 47. Retrieve orders placed by customers from São Paulo using subquery
SELECT order_id, customer_id, order_status 
FROM orders 
WHERE customer_id IN (SELECT customer_id FROM customers WHERE customer_state = 'SP');

-- 48. Correlated Subquery: Find products that are the most expensive in their category
SELECT p1.product_id, p1.product_category_name, p1.product_base_price 
FROM products p1
WHERE p1.product_base_price = (
    SELECT MAX(p2.product_base_price) 
    FROM products p2 
    WHERE p2.product_category_name = p1.product_category_name
);

-- 49. CTE to calculate monthly revenue trends
WITH MonthlySales AS (
    SELECT 
        DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS sale_month,
        SUM(price * quantity) AS monthly_revenue
    FROM orders o
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY DATE_FORMAT(order_purchase_timestamp, '%Y-%m')
)
SELECT sale_month, monthly_revenue 
FROM MonthlySales 
ORDER BY sale_month ASC;

-- 50. CTE to identify the top 5 spending customers
WITH CustomerSpend AS (
    SELECT c.customer_unique_id, SUM(oi.price * oi.quantity) AS total_spend
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY c.customer_unique_id
)
SELECT customer_unique_id, total_spend 
FROM CustomerSpend 
ORDER BY total_spend DESC 
LIMIT 5;

-- 51. Subquery in SELECT: List products and their difference from the category average price
SELECT 
    product_id, 
    product_category_name, 
    product_base_price,
    product_base_price - (
        SELECT AVG(p2.product_base_price) 
        FROM products p2 
        WHERE p2.product_category_name = p1.product_category_name
    ) AS price_diff_from_avg
FROM products p1
LIMIT 10;

-- 52. Subquery with EXISTS: Retrieve sellers who have had at least one order canceled
SELECT s.seller_id, s.seller_city, s.seller_state 
FROM sellers s
WHERE EXISTS (
    SELECT 1 
    FROM order_items oi
    INNER JOIN orders o ON oi.order_id = o.order_id
    WHERE oi.seller_id = s.seller_id AND o.order_status = 'canceled'
);

-- 53. CTE to compute repeat purchase status of users
WITH UserPurchaseCounts AS (
    SELECT c.customer_unique_id, COUNT(o.order_id) AS order_count
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
)
SELECT 
    order_count AS orders_placed, 
    COUNT(customer_unique_id) AS customer_count,
    (COUNT(customer_unique_id) * 100.0 / (SELECT COUNT(*) FROM (SELECT DISTINCT customer_unique_id FROM customers) AS total)) AS customer_pct
FROM UserPurchaseCounts
GROUP BY order_count
ORDER BY order_count ASC;

-- 54. CTE to calculate average review score by seller
WITH SellerReviews AS (
    SELECT oi.seller_id, r.review_score
    FROM order_items oi
    INNER JOIN reviews r ON oi.order_id = r.order_id
)
SELECT seller_id, AVG(review_score) AS avg_seller_rating, COUNT(review_score) AS total_ratings
FROM SellerReviews
GROUP BY seller_id
HAVING total_ratings >= 5
ORDER BY avg_seller_rating DESC
LIMIT 10;

-- 55. Subquery to find orders where delivery took longer than the estimated time
SELECT order_id, customer_id, DATEDIFF(order_delivered_customer_date, order_purchase_timestamp) AS actual_delivery_days, DATEDIFF(order_estimated_delivery_date, order_purchase_timestamp) AS estimated_delivery_days
FROM orders 
WHERE order_status = 'delivered' 
  AND DATEDIFF(order_delivered_customer_date, order_purchase_timestamp) > DATEDIFF(order_estimated_delivery_date, order_purchase_timestamp);

-- 56. CTE to calculate regional shipping delay percentages
WITH RegionalShipping AS (
    SELECT c.customer_state, 
           CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 ELSE 0 END AS is_delayed
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    WHERE o.order_status = 'delivered'
)
SELECT customer_state, COUNT(*) AS total_delivered, SUM(is_delayed) AS total_delayed, (SUM(is_delayed) * 100.0 / COUNT(*)) AS delay_pct
FROM RegionalShipping
GROUP BY customer_state
ORDER BY delay_pct DESC;

-- 57. Nested subquery to find categories that contain products with returns
SELECT product_category_name_english 
FROM categories 
WHERE product_category_name IN (
    SELECT DISTINCT product_category_name 
    FROM products 
    WHERE product_id IN (
        SELECT DISTINCT product_id FROM returns WHERE return_status = 'approved'
    )
);

-- 58. CTE to calculate the revenue concentration by category
WITH CategoryRevenue AS (
    SELECT p.product_category_name, SUM(oi.price * oi.quantity) AS revenue
    FROM order_items oi
    INNER JOIN products p ON oi.product_id = p.product_id
    GROUP BY p.product_category_name
)
SELECT product_category_name, revenue, (revenue * 100.0 / (SELECT SUM(price * quantity) FROM order_items)) AS revenue_share_pct
FROM CategoryRevenue
ORDER BY revenue DESC;

-- 59. CTE to analyze seasonal sales variation (Quarterly sales value)
WITH QuarterlySales AS (
    SELECT 
        YEAR(order_purchase_timestamp) AS yr,
        QUARTER(order_purchase_timestamp) AS qtr,
        SUM(price * quantity) AS total_sales
    FROM orders o
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY YEAR(order_purchase_timestamp), QUARTER(order_purchase_timestamp)
)
SELECT yr, qtr, total_sales 
FROM QuarterlySales 
ORDER BY yr ASC, qtr ASC;

-- 60. Subquery to identify users whose first order was in 2024 and who also ordered in 2026
SELECT DISTINCT customer_unique_id 
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
WHERE YEAR(o.order_purchase_timestamp) = 2024
  AND customer_unique_id IN (
      SELECT DISTINCT customer_unique_id 
      FROM customers c2
      INNER JOIN orders o2 ON c2.customer_id = o2.customer_id
      WHERE YEAR(o2.order_purchase_timestamp) = 2026
  );


-- ====================================================================
-- SECTION 5: Control Flow and Conditional Operations (Queries 61-70)
-- ====================================================================

-- 61. Categorize products into Price Brackets using CASE
SELECT 
    product_id, 
    product_base_price,
    CASE 
        WHEN product_base_price < 50 THEN 'Low Value'
        WHEN product_base_price BETWEEN 50 AND 200 THEN 'Medium Value'
        WHEN product_base_price BETWEEN 200 AND 800 THEN 'High Value'
        ELSE 'Premium Value'
    END AS price_tier
FROM products;

-- 62. Calculate refund percentage depending on return status
SELECT 
    return_id, 
    return_status,
    CASE 
        WHEN return_status = 'approved' THEN '100% Refunded'
        WHEN return_status = 'rejected' THEN '0% Refunded (Rejected)'
        ELSE 'Refund Processing (Pending)'
    END AS refund_state
FROM returns;

-- 63. Use COALESCE to handle null review comment titles
SELECT 
    review_id, 
    review_score, 
    COALESCE(review_comment_title, 'No Title Provided') AS clean_title 
FROM reviews 
LIMIT 10;

-- 64. Use CASE to label delivery status compared to estimated date
SELECT 
    order_id, 
    order_delivered_customer_date, 
    order_estimated_delivery_date,
    CASE 
        WHEN order_delivered_customer_date IS NULL THEN 'Not Delivered'
        WHEN order_delivered_customer_date <= order_estimated_delivery_date THEN 'On Time / Early'
        ELSE 'Delayed'
    END AS delivery_performance
FROM orders;

-- 65. UNION: Combine names of cities with customers and cities with sellers
SELECT DISTINCT customer_city AS city_name, 'Customer City' AS source_type FROM customers
UNION
SELECT DISTINCT seller_city AS city_name, 'Seller City' AS source_type FROM sellers
LIMIT 15;

-- 66. UNION ALL: Combine all SP state locations for review
SELECT customer_city AS SP_City FROM customers WHERE customer_state = 'SP'
UNION ALL
SELECT seller_city AS SP_City FROM sellers WHERE seller_state = 'SP'
LIMIT 15;

-- 67. COALESCE order approved timestamp, falling back to purchase date if payment approval was instant
SELECT 
    order_id, 
    order_purchase_timestamp, 
    COALESCE(order_approved_at, order_purchase_timestamp) AS final_approval_time 
FROM orders 
LIMIT 10;

-- 68. Classify review score sentiment using CASE
SELECT 
    review_id, 
    review_score,
    CASE 
        WHEN review_score >= 4 THEN 'Positive'
        WHEN review_score = 3 THEN 'Neutral'
        ELSE 'Negative'
    END AS customer_sentiment
FROM reviews;

-- 69. Calculate order status performance metrics conditionally
SELECT 
    COUNT(CASE WHEN order_status = 'delivered' THEN 1 END) AS delivered_count,
    COUNT(CASE WHEN order_status = 'canceled' THEN 1 END) AS canceled_count,
    COUNT(CASE WHEN order_status NOT IN ('delivered', 'canceled') THEN 1 END) AS ongoing_count,
    COUNT(*) AS total_orders
FROM orders;

-- 70. Group customers into Recency segments based on days since last purchase
WITH UserRecency AS (
    SELECT 
        c.customer_unique_id,
        DATEDIFF('2026-06-15 23:59:59', MAX(o.order_purchase_timestamp)) AS recency_days
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
)
SELECT 
    customer_unique_id, 
    recency_days,
    CASE 
        WHEN recency_days <= 30 THEN 'Active (0-30 days)'
        WHEN recency_days BETWEEN 31 AND 180 THEN 'Warm (31-180 days)'
        WHEN recency_days BETWEEN 181 AND 365 THEN 'Cold (181-365 days)'
        ELSE 'Inactive (1yr+)'
    END AS activity_status
FROM UserRecency;


-- ====================================================================
-- SECTION 6: Analytical Window Functions (Queries 71-85)
-- ====================================================================

-- 71. ROW_NUMBER: Row number assigned to items in each order to sequence them
SELECT 
    order_id, 
    product_id, 
    price,
    ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY price DESC) AS item_price_rank
FROM order_items
LIMIT 15;

-- 72. RANK: Rank categories by total products count
SELECT 
    product_category_name, 
    COUNT(*) AS prod_count,
    RANK() OVER (ORDER BY COUNT(*) DESC) AS category_rank
FROM products
GROUP BY product_category_name;

-- 73. DENSE_RANK: Dense rank sellers by revenue generated
SELECT 
    seller_id, 
    revenue,
    DENSE_RANK() OVER (ORDER BY revenue DESC) AS seller_revenue_rank
FROM (
    SELECT seller_id, SUM(price * quantity) AS revenue 
    FROM order_items 
    GROUP BY seller_id
) AS SellerRevenue
LIMIT 10;

-- 74. NTILE: Divide customers into 4 quartiles based on total purchase monetary value
SELECT 
    customer_unique_id,
    total_spend,
    NTILE(4) OVER (ORDER BY total_spend DESC) AS spend_quartile
FROM (
    SELECT c.customer_unique_id, SUM(oi.price * oi.quantity) AS total_spend
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY c.customer_unique_id
) AS CustMonetary
LIMIT 15;

-- 75. Running Total of daily sales revenue using SUM OVER
SELECT 
    order_date,
    daily_revenue,
    SUM(daily_revenue) OVER (ORDER BY order_date) AS running_total_revenue
FROM (
    SELECT DATE(order_purchase_timestamp) AS order_date, SUM(price * quantity) AS daily_revenue
    FROM orders o
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY DATE(order_purchase_timestamp)
) AS DailyRevenue
LIMIT 15;

-- 76. LEAD: Find the purchase date of the next order for repeat customers
SELECT 
    customer_unique_id,
    order_id,
    order_purchase_timestamp AS current_order_date,
    LEAD(order_purchase_timestamp) OVER (PARTITION BY customer_unique_id ORDER BY order_purchase_timestamp) AS next_order_date
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
LIMIT 20;

-- 77. LAG: Compute the interval (days) between consecutive purchases of repeat users
WITH ConsecutivePurchases AS (
    SELECT 
        c.customer_unique_id,
        o.order_purchase_timestamp AS current_date,
        LAG(o.order_purchase_timestamp) OVER (PARTITION BY customer_unique_id ORDER BY o.order_purchase_timestamp) AS prev_date
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
)
SELECT 
    customer_unique_id, 
    current_date, 
    prev_date,
    DATEDIFF(current_date, prev_date) AS days_between_purchases
FROM ConsecutivePurchases
WHERE prev_date IS NOT NULL;

-- 78. Moving Average: 7-day moving average of daily orders placed
WITH DailyOrderCounts AS (
    SELECT DATE(order_purchase_timestamp) AS order_date, COUNT(*) AS order_count
    FROM orders
    GROUP BY DATE(order_purchase_timestamp)
)
SELECT 
    order_date,
    order_count,
    AVG(order_count) OVER (ORDER BY order_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS 7_day_moving_avg
FROM DailyOrderCounts;

-- 79. ROW_NUMBER: Select only the most recent order for each customer profile
WITH CustomerOrderRanks AS (
    SELECT 
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp,
        ROW_NUMBER() OVER (PARTITION BY c.customer_unique_id ORDER BY o.order_purchase_timestamp DESC) AS order_recency_rank
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
)
SELECT customer_unique_id, order_id, order_purchase_timestamp 
FROM CustomerOrderRanks
WHERE order_recency_rank = 1
LIMIT 10;

-- 80. Running Total: running sum of products added to inventory by category
SELECT 
    product_category_name,
    product_id,
    product_base_price,
    SUM(product_base_price) OVER (PARTITION BY product_category_name ORDER BY product_id) AS cumulative_category_value
FROM products;

-- 81. PERCENT_RANK: Percentile rank of products by price
SELECT 
    product_id, 
    product_category_name, 
    product_base_price,
    PERCENT_RANK() OVER (ORDER BY product_base_price DESC) AS price_percent_rank
FROM products
LIMIT 10;

-- 82. FIRST_VALUE: Retrieve the first order ID placed by each unique user
SELECT DISTINCT 
    c.customer_unique_id,
    FIRST_VALUE(o.order_id) OVER (PARTITION BY c.customer_unique_id ORDER BY o.order_purchase_timestamp ASC) AS first_order_id,
    FIRST_VALUE(o.order_purchase_timestamp) OVER (PARTITION BY c.customer_unique_id ORDER BY o.order_purchase_timestamp ASC) AS first_purchase_date
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
LIMIT 15;

-- 83. LAST_VALUE: Find the last review score left by each user (handling bounds)
SELECT DISTINCT 
    c.customer_unique_id,
    LAST_VALUE(r.review_score) OVER (
        PARTITION BY c.customer_unique_id 
        ORDER BY r.review_creation_date 
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS last_review_score
FROM reviews r
INNER JOIN orders o ON r.order_id = o.order_id
INNER JOIN customers c ON o.customer_id = c.customer_id
LIMIT 15;

-- 84. LAG: Check the price changes for consecutive order items within the same order
SELECT 
    order_id,
    product_id,
    price,
    LAG(price) OVER (PARTITION BY order_id ORDER BY order_item_id) AS previous_item_price,
    price - LAG(price) OVER (PARTITION BY order_id ORDER BY order_item_id) AS price_diff
FROM order_items
LIMIT 15;

-- 85. 30-Day Moving Average: 30-day moving average of daily revenue
WITH DailySalesRevenue AS (
    SELECT DATE(order_purchase_timestamp) AS order_date, SUM(price * quantity) AS daily_revenue
    FROM orders o
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY DATE(order_purchase_timestamp)
)
SELECT 
    order_date,
    daily_revenue,
    AVG(daily_revenue) OVER (ORDER BY order_date ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS 30_day_moving_revenue_avg
FROM DailySalesRevenue
LIMIT 30;


-- ====================================================================
-- SECTION 7: Business-Level KPI and Metrics Queries (Queries 86-95)
-- ====================================================================

-- 86. Repeat Customer Rate: Calculate the percentage of users with >1 orders
SELECT 
    (COUNT(CASE WHEN order_count > 1 THEN 1 END) * 100.0 / COUNT(*)) AS repeat_customer_rate
FROM (
    SELECT c.customer_unique_id, COUNT(o.order_id) AS order_count
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
) AS CustomerOrders;

-- 87. Customer Retention Rate (CRR) & Churn Rate: Cohort Analysis
WITH Cohort2024 AS (
    SELECT DISTINCT c.customer_unique_id 
    FROM customers c
    INNER JOIN orders o ON c.customer_id = o.customer_id
    WHERE YEAR(o.order_purchase_timestamp) = 2024
),
CohortRetained AS (
    SELECT DISTINCT c.customer_unique_id
    FROM customers c
    INNER JOIN orders o ON c.customer_id = o.customer_id
    INNER JOIN Cohort2024 c24 ON c.customer_unique_id = c24.customer_unique_id
    WHERE YEAR(o.order_purchase_timestamp) IN (2025, 2026)
)
SELECT 
    (SELECT COUNT(*) FROM Cohort2024) AS original_2024_customers,
    (SELECT COUNT(*) FROM CohortRetained) AS retained_customers,
    ((SELECT COUNT(*) FROM CohortRetained) * 100.0 / (SELECT COUNT(*) FROM Cohort2024)) AS customer_retention_rate,
    (100.0 - ((SELECT COUNT(*) FROM CohortRetained) * 100.0 / (SELECT COUNT(*) FROM Cohort2024))) AS customer_churn_rate;

-- 88. Average Order Value (AOV)
SELECT SUM(price * quantity) / COUNT(DISTINCT order_id) AS average_order_value FROM order_items;

-- 89. CLV Estimation: Average Spend * Purchase Frequency (Total Orders/Customers)
WITH CustomerCLVMeta AS (
    SELECT 
        c.customer_unique_id,
        COUNT(o.order_id) AS total_orders,
        SUM(oi.price * oi.quantity) AS total_spend
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY c.customer_unique_id
)
SELECT 
    AVG(total_spend / total_orders) AS avg_order_value,
    AVG(total_orders) AS avg_orders_per_customer,
    AVG(total_spend) AS avg_clv
FROM CustomerCLVMeta;

-- 90. Pareto 80/20 spend rule validation: Find the customer base generating 80% revenue
WITH CustomerSales AS (
    SELECT c.customer_unique_id, SUM(oi.price * oi.quantity) AS spend
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY c.customer_unique_id
),
RunningSales AS (
    SELECT 
        customer_unique_id,
        spend,
        SUM(spend) OVER (ORDER BY spend DESC) AS cumulative_spend,
        (SELECT SUM(price * quantity) FROM order_items) AS total_revenue,
        ROW_NUMBER() OVER (ORDER BY spend DESC) AS row_num,
        (SELECT COUNT(DISTINCT customer_unique_id) FROM customers) AS total_customers
    FROM CustomerSales
)
SELECT 
    row_num AS customer_count,
    (row_num * 100.0 / total_customers) AS customer_percentage,
    spend AS customer_spend,
    (cumulative_spend * 100.0 / total_revenue) AS cumulative_revenue_percentage
FROM RunningSales
WHERE (cumulative_spend * 100.0 / total_revenue) <= 80.05
ORDER BY row_num DESC
LIMIT 1;

-- 91. ABC Product Analysis: Group products into classes based on revenue share
WITH ProductRevenue AS (
    SELECT product_id, SUM(price * quantity) AS revenue
    FROM order_items
    GROUP BY product_id
),
ProductCumulative AS (
    SELECT 
        product_id,
        revenue,
        SUM(revenue) OVER (ORDER BY revenue DESC) AS cum_revenue,
        (SELECT SUM(price * quantity) FROM order_items) AS total_revenue
    FROM ProductRevenue
),
ABCClassification AS (
    SELECT 
        product_id,
        revenue,
        (cum_revenue / total_revenue) AS cum_share,
        CASE 
            WHEN (cum_revenue / total_revenue) <= 0.70 THEN 'A'
            WHEN (cum_revenue / total_revenue) <= 0.90 THEN 'B'
            ELSE 'C'
        END AS abc_class
    FROM ProductCumulative
)
SELECT 
    abc_class,
    COUNT(product_id) AS product_count,
    (COUNT(product_id) * 100.0 / (SELECT COUNT(*) FROM products)) AS product_pct,
    SUM(revenue) AS total_class_revenue,
    (SUM(revenue) * 100.0 / (SELECT SUM(price * quantity) FROM order_items)) AS revenue_pct
FROM ABCClassification
GROUP BY abc_class
ORDER BY abc_class;

-- 92. RFM Quintiles calculation using Window NTILE
WITH CustomerRFM AS (
    SELECT 
        c.customer_unique_id,
        DATEDIFF('2026-06-15 23:59:59', MAX(o.order_purchase_timestamp)) AS recency,
        COUNT(o.order_id) AS frequency,
        SUM(oi.price * oi.quantity) AS monetary
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY c.customer_unique_id
),
RFM_Scores AS (
    SELECT 
        customer_unique_id,
        recency, frequency, monetary,
        NTILE(5) OVER (ORDER BY recency ASC) AS r_score_inv, -- recency lower is better
        NTILE(5) OVER (ORDER BY frequency DESC) AS f_score,
        NTILE(5) OVER (ORDER BY monetary DESC) AS m_score
    FROM CustomerRFM
)
SELECT 
    customer_unique_id,
    recency, frequency, monetary,
    (6 - r_score_inv) AS r_score, -- Invert score so low recency days = 5
    f_score, m_score
FROM RFM_Scores
LIMIT 15;

-- 93. Month-over-Month Revenue Growth Rate
WITH MonthlySales AS (
    SELECT 
        DATE_FORMAT(order_purchase_timestamp, '%Y-%m') AS sale_month,
        SUM(price * quantity) AS revenue
    FROM orders o
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY DATE_FORMAT(order_purchase_timestamp, '%Y-%m')
),
MonthlyComparisons AS (
    SELECT 
        sale_month,
        revenue,
        LAG(revenue) OVER (ORDER BY sale_month) AS prev_month_revenue
    FROM MonthlySales
)
SELECT 
    sale_month,
    revenue AS current_month_revenue,
    prev_month_revenue,
    ((revenue - prev_month_revenue) * 100.0 / prev_month_revenue) AS mom_growth_rate_pct
FROM MonthlyComparisons
WHERE prev_month_revenue IS NOT NULL
ORDER BY sale_month;

-- 94. Product Category Return Rates (defective returns vs total items sold)
SELECT 
    p.product_category_name,
    COUNT(oi.order_item_id) AS items_sold,
    COUNT(r.return_id) AS return_requests,
    (COUNT(r.return_id) * 100.0 / COUNT(oi.order_item_id)) AS return_rate_pct,
    COUNT(CASE WHEN r.return_reason = 'defective' THEN 1 END) AS defective_returns_count
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
LEFT JOIN returns r ON oi.order_id = r.order_id AND oi.product_id = r.product_id
GROUP BY p.product_category_name
ORDER BY return_rate_pct DESC;

-- 95. Net Promoter Score (NPS) / Satisfaction Index based on Reviews (CSAT equivalent)
SELECT 
    COUNT(review_id) AS total_reviews,
    AVG(review_score) AS average_review_score,
    (COUNT(CASE WHEN review_score >= 4 THEN 1 END) * 100.0 / COUNT(*)) AS positive_pct,
    (COUNT(CASE WHEN review_score = 3 THEN 1 END) * 100.0 / COUNT(*)) AS neutral_pct,
    (COUNT(CASE WHEN review_score <= 2 THEN 1 END) * 100.0 / COUNT(*)) AS negative_pct,
    ((COUNT(CASE WHEN review_score >= 5 THEN 1 END) - COUNT(CASE WHEN review_score <= 3 THEN 1 END)) * 100.0 / COUNT(*)) AS satisfaction_index_score
FROM reviews;


-- ====================================================================
-- SECTION 8: Views, Stored Procedures, and Tuning (Queries 96-100)
-- ====================================================================

-- 96. Create View: Customer Order Lifetime Summary View
CREATE OR REPLACE VIEW view_customer_lifetime_summary AS
SELECT 
    c.customer_unique_id,
    c.customer_city,
    c.customer_state,
    MIN(o.order_purchase_timestamp) AS first_order_date,
    MAX(o.order_purchase_timestamp) AS last_order_date,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.price * oi.quantity) AS total_spend,
    SUM(oi.freight_value) AS total_freight_paid,
    AVG(r.review_score) AS average_given_rating
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
LEFT JOIN reviews r ON o.order_id = r.order_id
GROUP BY c.customer_unique_id, c.customer_city, c.customer_state;

-- Test View selection
SELECT * FROM view_customer_lifetime_summary LIMIT 10;

-- 97. Create View: Daily Operational Logistics Dashboard View
CREATE OR REPLACE VIEW view_daily_logistics_status AS
SELECT 
    DATE(o.order_purchase_timestamp) AS purchase_date,
    COUNT(o.order_id) AS orders_placed,
    COUNT(CASE WHEN o.order_status = 'delivered' THEN 1 END) AS orders_delivered,
    COUNT(CASE WHEN o.order_status = 'canceled' THEN 1 END) AS orders_canceled,
    AVG(DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp)) AS avg_shipping_days,
    SUM(CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 ELSE 0 END) AS delayed_deliveries
FROM orders o
GROUP BY DATE(o.order_purchase_timestamp);

-- Test View selection
SELECT * FROM view_daily_logistics_status LIMIT 10;

-- 98. Stored Procedure: Get monthly sales performance report for a specific state
DELIMITER //

CREATE PROCEDURE sp_monthly_sales_by_state(IN input_state VARCHAR(5))
BEGIN
    SELECT 
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS sale_month,
        COUNT(DISTINCT o.order_id) AS orders_count,
        SUM(oi.price * oi.quantity) AS total_revenue,
        SUM(oi.freight_value) AS total_freight
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    INNER JOIN order_items oi ON o.order_id = oi.order_id
    WHERE c.customer_state = input_state
    GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
    ORDER BY sale_month ASC;
END //

DELIMITER ;

-- Test Procedure execution (Uncomment to execute)
-- CALL sp_monthly_sales_by_state('SP');

-- 99. Stored Procedure: Profile customer spend tier and last review score
DELIMITER //

CREATE PROCEDURE sp_profile_customer_summary(IN input_customer_unique_id VARCHAR(50))
BEGIN
    SELECT 
        customer_unique_id,
        total_orders,
        total_spend,
        average_given_rating,
        CASE 
            WHEN total_spend >= 1500 THEN 'Platinum Spender'
            WHEN total_spend BETWEEN 500 AND 1499 THEN 'Gold Spender'
            ELSE 'Silver Spender'
        END AS spend_segment
    FROM view_customer_lifetime_summary
    WHERE customer_unique_id = input_customer_unique_id;
END //

DELIMITER ;

-- Test Procedure execution (Uncomment to execute)
-- CALL sp_profile_customer_summary('usr_000001');

-- 100. Database Index Optimization: Verify Index status for orders table tuning
SHOW INDEX FROM orders;
